### ISSUE TITLE
Cannot build extension

### ISSUE THREAD

**Issue by DEFAULTTEXHAPb** [sthenic/vls-vscode#1]
Running `npm run compile` on Windows 10 gives this error:
```
C:\Users\{my_name}\Downloads\vls-vscode-master\vls-vscode-master>npm run compile

> vls-vscode@0.1.0 compile C:\Users\{my_name}\Downloads\vls-vscode-master\vls-vscode-master
> tsc -b

src/extension.ts:1:45 - error TS2307: Cannot find module 'vscode' or its corresponding type declarations.

1 import { workspace, ExtensionContext } from "vscode";
                                              ~~~~~~~~~~~~~

src/extension.ts:7:8 - error TS2307: Cannot find module 'vscode-languageclient' or its corresponding type declarations.

7 } from "vscode-languageclient";
         ~~~~~~~~~~~~~~~~~~~~~~~

src/extension.ts:36:31 - error TS2304: Cannot find name 'Thenable'.

36 export function deactivate(): Thenable<void> | undefined {
                                 ~~~~~~~~


Found 3 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vls-vscode@0.1.0 compile: `tsc -b`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vls-vscode@0.1.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\{my_name}\AppData\Roaming\npm-cache\_logs\2021-09-08T09_23_07_614Z-debug.log
```
Debug log shows this:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle vls-vscode@0.1.0~precompile: vls-vscode@0.1.0
6 info lifecycle vls-vscode@0.1.0~compile: vls-vscode@0.1.0
7 verbose lifecycle vls-vscode@0.1.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle vls-vscode@0.1.0~compile: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\{my_name}\Downloads\vls-vscode-master\vls-vscode-master\node_modules\.bin;C:\Users\{my_name}\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\msys64\mingw64\bin;C:\Program Files\nodejs\;C:\Users\{my_name}\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\Microsoft VS Code\bin;C:\msys64\mingw64\bin;C:\Users\{my_name}\AppData\Roaming\npm
9 verbose lifecycle vls-vscode@0.1.0~compile: CWD: C:\Users\{my_name}\Downloads\vls-vscode-master\vls-vscode-master
10 silly lifecycle vls-vscode@0.1.0~compile: Args: [ '/d /s /c', 'tsc -b' ]
11 silly lifecycle vls-vscode@0.1.0~compile: Returned: code: 1  signal: null
12 info lifecycle vls-vscode@0.1.0~compile: Failed to exec compile script
13 verbose stack Error: vls-vscode@0.1.0 compile: `tsc -b`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid vls-vscode@0.1.0
15 verbose cwd C:\Users\{my_name}\Downloads\vls-vscode-master\vls-vscode-master
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error vls-vscode@0.1.0 compile: `tsc -b`
22 error Exit status 1
23 error Failed at the vls-vscode@0.1.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
All dependencies listed in `devDependencies` of `package.json` were installed

**Comment by sthenic** [comment]
I made some changes in 7cd5e5841fb47a3acf4a278ec077f4699b51e931 to make it build with new versions of VSCode.

I got your error initially, but was able to fix it by running `npm install` before running `npm run compile`.

To make a VSCode extension package, use [`vsce`](https://github.com/microsoft/vscode-vsce) (`npm install -g vsce`) and run `vsce package`.

You should get a `.vsix` file which you can install with `code --install-extension *.vsix`.

**Comment by DEFAULTTEXHAPb** [comment]
It works now. Extension compiles and runs successfuly. Thanks
